const INPUT_FOLDER_NAME = "uploads/";
const OUTPUT_FOLDER_NAME = "compressed_images";

const MAX_FILES_ENTERED = 10;

const ARCHIVE_FORMAT = "zip";
const ARCHIVE_LEVEL = 9;

module.exports = { INPUT_FOLDER_NAME, OUTPUT_FOLDER_NAME, MAX_FILES_ENTERED, ARCHIVE_FORMAT, ARCHIVE_LEVEL };
